# Generated by Django 2.2.2 on 2019-07-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_empresa'),
        ('funcionarios', '0004_auto_20190630_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='departamentos',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departamentos.Departamento'),
        ),
    ]
