# Generated by Django 2.2.3 on 2019-07-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_listdocto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListDocto',
        ),
    ]
