# Generated by Django 2.2.2 on 2019-06-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20190630_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Atalho'),
            preserve_default=False,
        ),
    ]
