# Generated by Django 2.2.2 on 2019-06-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['razao_social']},
        ),
    ]
