# Generated by Django 2.2.2 on 2019-06-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20190630_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=100),
        ),
    ]
