# Generated by Django 2.2.3 on 2019-08-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='I900Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('cod_empresa', models.CharField(max_length=3)),
                ('cod_filial', models.CharField(max_length=6)),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField()),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
