# Generated by Django 2.2.3 on 2019-07-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_auto_20190730_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i001group',
            name='control',
            field=models.SlugField(verbose_name='Atalho'),
        ),
        migrations.AlterField(
            model_name='i002company',
            name='control',
            field=models.SlugField(verbose_name='Atalho'),
        ),
        migrations.AlterField(
            model_name='i003branch',
            name='control',
            field=models.SlugField(verbose_name='Atalho'),
        ),
    ]
