# Generated by Django 2.2.3 on 2019-07-31 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_auto_20190731_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='i001group',
            old_name='control',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='i002company',
            old_name='control',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='i003branch',
            old_name='control',
            new_name='slug',
        ),
    ]
