# Generated by Django 2.2.3 on 2019-08-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0004_auto_20190731_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i003branch',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corporate.I002Company'),
        ),
    ]
